// src/app/components/about/about.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-about',
  standalone: true,
  template: `
    <section class="section__container about__container" id="about">
      <div class="about__image">
        <div class="about__image-frame">
          <img src="assets/images/aboutme.jpeg" alt="Satish Pakalapati" />
        </div>
      </div>

      <div class="about__content">
        <div class="section__tag">About Me</div>
        <h2 class="section__header">Passionate About <span>Data and Innovation</span></h2>
        <p>
          I'm Satish Pakalapati, a B.Tech Computer Science student at Lovely Professional University,
          building a strong path across Data Science, Digital Marketing, and full-stack development.
        </p>
        <h4>
          I enjoy crafting dynamic dashboards, machine learning models, SQL analysis, and polished web experiences that turn
          rough ideas into useful outcomes.
        </h4>
        <div class="about-chips">
          <span><i class="ri-graduation-cap-line"></i>LPU B.Tech CSE</span>
          <span><i class="ri-bar-chart-2-line"></i>Data Analyst</span>
          <span><i class="ri-code-s-slash-line"></i>Full Stack Dev</span>
        </div>
        <div class="about__btns">
          <a href="/Resume.pdf" target="_blank" class="download__btn" rel="noopener noreferrer"><i class="ri-download-2-line"></i>Access My CV</a>
          <a href="mailto:satishpakalapati65@gmail.com" title="Email"><i class="ri-mail-fill"></i></a>
          <a href="https://github.com/Satish-970" target="_blank" rel="noopener noreferrer" title="GitHub"><i class="ri-github-fill"></i></a>
          <a href="https://www.linkedin.com/in/satishpakalapati/" target="_blank" rel="noopener noreferrer" title="LinkedIn"><i class="ri-linkedin-fill"></i></a>
        </div>
      </div>
    </section>
  `,
})
export class AboutComponent {}

// src/components/About.jsx
import { useEffect } from 'react';
import ScrollReveal from 'scrollreveal';
import aboutImg from '../assets/images/IMG_6234.jpg';

const About = () => {
    useEffect(() => {
        ScrollReveal().reveal(".about__image img", {
            distance: "50px",
            origin: "left",
            duration: 1000,
            viewFactor: 0.5,
        });
        ScrollReveal().reveal(".about__content .section__header", {
            distance: "50px",
            origin: "bottom",
            duration: 1000,
            delay: 500,
        });
        ScrollReveal().reveal(".about__content p", {
            distance: "50px",
            origin: "bottom",
            duration: 1000,
            delay: 1000,
        });
        ScrollReveal().reveal(".about__content h4", {
            distance: "50px",
            origin: "bottom",
            duration: 1000,
            delay: 1500,
        });
        ScrollReveal().reveal(".about__btns", {
            distance: "50px",
            origin: "bottom",
            duration: 1000,
            delay: 2000,
        });
    }, []);
    return (
        <section className="section__container about__container" id="about">
            <div className="about__image">
                <img src={aboutImg} alt="about" loading="lazy" />
            </div>
            <div className="about__content">
                <h2 className="section__header">About me</h2>
                <p>Satish Pakalapati
                    A relentless B.Tech Computer Science student at Lovely Professional University,
                    Mastering the art of Data Science and Digital Marketing with unmatched drive.
                </p>
                <h4>
                    Expertise
                    Fueled by a passion for innovation, Excels at crafting dynamic dashboards and engineering cutting-edge machine learning models.
                    Committed to pushing boundaries, Continuously hones expertise in emerging technologies,
                    Delivering high-impact solutions that redefine what's possible!.
                </h4>
                <div className="about__btns">
                    <a href="/Resume.pdf" target="_blank" className="download__btn" rel="noopener noreferrer">
                        Access My CV
                    </a>
                    <a href="mailto:satishpakalapati65@gmail.com"><i className="ri-mail-fill"></i></a>
                    <a href="https://github.com/Satish-970"><i className="ri-github-fill"></i></a>
                    <a href="https://www.linkedin.com/in/satishpakalapati/"><i className="ri-linkedin-fill"></i></a>
                    <a href="https://satishportfolio.blogspot.com/"><i className="ri-article-fill"></i></a>
                </div>
            </div>
        </section>
    );
};

export default About;
