// src/app/components/resume/resume.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-resume',
  standalone: true,
  imports: [CommonModule],
  template: `
    <section class="section__container client__container" id="resume" *ngIf="showOnly === 'resume'">
      <h2 class="section__header">Experience and <span>Education</span></h2>

      <h3 class="test">Work Experience</h3>
      <article class="testimonial__card1">
        <div class="resume-card__top">
          <div>
            <h3>Program Analyst Trainee (Intern)</h3>
            <h3 class="resume-org">Cognizant &mdash; <span>Full Stack Java Engineering</span></h3>
          </div>
          <span class="resume-date">Jan 2026 – May 2026</span>
        </div>
        <h5>Full Stack Java Developer Intern Details</h5>
        <ul>
          <li>Completed structured Full Stack Java Engineer training covering Spring Boot, Hibernate, REST APIs, and microservices architecture.</li>
          <li>Collaborated in a 6-member Agile team to deliver the CityCare platform across 4 sprints of 15 days each using Jira for tracking.</li>
          <li>Containerized services using Docker and managed Git-based collaborative workflows.</li>
          <li>Completed corporate behavioral training focused on workplace communication and teamwork.</li>
        </ul>
        <h4>Learnt Tech<span>: Java, Spring Boot, Hibernate, REST APIs, Docker, Git, Jira</span></h4>
      </article>

      <h3 class="test">Summer Training</h3>
      <article class="testimonial__card1">
        <div class="resume-card__top">
          <div>
            <a href="https://www.boardinfinity.com/programs/college-courses" target="_blank" rel="noopener noreferrer"><h3>Data Analyst Intern</h3></a>
            <h3 class="resume-org">Board Infinity <span>DBMS and SQL</span></h3>
          </div>
          <a href="/Resume.pdf" target="_blank" class="download__btn" rel="noopener noreferrer"><i class="ri-download-2-line"></i>Download CV</a>
        </div>
        <h5>Database Management Systems and SQL Proficiency</h5>
        <ul>
          <li>Mastered DBMS concepts including ER diagrams, normalization (1NF-3NF), and B/B+ Tree query optimization.</li>
          <li>Gained expertise in transaction management (ACID, serializability, concurrency control) and optimized structures.</li>
          <li>Proficient in SQL operations (joins, subqueries, grouping, CASE statements) using MySQL, PostgreSQL, and Oracle.</li>
        </ul>
        <h4>Learnt Tech<span>: MySQL, Oracle SQL, PostgreSQL, SQL</span></h4>
      </article>

      <h3 class="test">Education</h3>
      <div class="testimonial__grid">
        <article class="testimonial__card"><h2>B.Tech</h2><p>2022 - Present<br />Lovely Professional University</p><h4>CGPA: 8.24 / 10.00</h4></article>
        <article class="testimonial__card"><h2>Intermediate</h2><p>2020 - 2022<br />DKNP JR College</p><h4>Percentage: 96%</h4></article>
        <article class="testimonial__card"><h2>Secondary</h2><p>2019 - 2020<br />Sri Siddartha Educational Institutions</p><h4>Percentage: 97%</h4></article>
      </div>

      <h3 class="test">Achievements</h3>
      <article class="testimonial__card1">
        <ul style="padding-left: 1.2rem; display: flex; flex-direction: column; gap: 0.6rem; color: var(--text-muted);">
          <li>Participated in Code-a-Haunt coding competition (codingblocks.com)</li>
          <li>Participated in a Data Science Workshop (cbgo.live)</li>
        </ul>
      </article>
    </section>

    <section class="section__container" id="certifications" *ngIf="showOnly === 'certifications'">
      <h2 class="section__header">Certifications and <span>Courses</span></h2>
      <div class="cert__grid">
        <article class="cert__card" *ngFor="let cert of certificates">
          <div class="cert__card-logo">{{ cert[0] }}</div>
          <img class="cert__card-img" [src]="cert[1]" [alt]="cert[0] + ' certificate'" />
          <p class="cert__card-desc">{{ cert[2] }}</p>
          <a class="cert__card-link" [href]="cert[3]" target="_blank" rel="noopener noreferrer">View Certificate <i class="ri-arrow-right-line"></i></a>
        </article>
      </div>
    </section>
  `,
})
export class ResumeComponent {
  @Input() showOnly: 'resume' | 'certifications' = 'resume';

  readonly certificates = [
    ['NPTEL', 'assets/images/12210470_MOOC_DZU2MXFCertificate_page-0001.jpg', 'Cloud Computing: Swayam cloud technology foundations certificate.', 'https://drive.google.com/file/d/1kXMl26U8M9dGRxv2W_9ZGZ5N3DfTL2JC/view?usp=sharing'],
    ['Coursera', 'assets/images/12210470_MOOC_7VK5AUXCertificate_page-0001.jpg', 'Supervised Machine Learning: Regression and Classification from Coursera.', 'https://drive.google.com/file/d/10To75UJpChRRsKQdrSanRagJ7EbPhhMp/view?usp=sharing'],
    ['Coursera', 'assets/images/12210470_MOOC_PVXX77WCertificate_page-0001.jpg', 'Data Visualization and Data Analysis course covering Tableau and analytics.', 'https://drive.google.com/file/d/1wL3HxfTMfYB-OstuJikaRAdDZVYf3-s3/view?usp=sharing'],
    ['Spring Board', 'assets/images/genai.jpg', 'Principles of Gen AI certificate from Spring Board.', ''],
    ['Coursera', 'assets/images/excel.jpg', 'Excel Skills for Data Analytics and Visualization from Coursera.', ''],
    ['HackerRank', 'assets/images/python_basic certificate_page-0001.jpg', 'Python certification showing core programming and problem-solving skills.', 'https://www.hackerrank.com/certificates/b18906a3a19c'],
  ];
}

// src/components/Resume.jsx
import { useEffect } from 'react';
import ScrollReveal from 'scrollreveal';
import cert1 from '../assets/images/12210470_MOOC_DZU2MXFCertificate_page-0001.jpg';
import cert2 from '../assets/images/12210470_MOOC_7VK5AUXCertificate_page-0001.jpg';
import cert3 from '../assets/images/python_basic certificate_page-0001.jpg';
import cert4 from '../assets/images/12210470_MOOC_PVXX77WCertificate_page-0001.jpg';
import cert5 from '../assets/images/COURSERA_CPP_page-0001.jpg';

const Resume = () => {
    useEffect(() => {
        ScrollReveal().reveal(".testimonial__card", {
            distance: "50px",
            origin: "bottom",
            duration: 1000,
            interval: 500,
            viewFactor: 0.5,
        });
        ScrollReveal().reveal(".testimonial__card1", {
            distance: "50px",
            origin: "bottom",
            duration: 1000
        });
    }, []);

    return (
        <section className="section__container client__container" id="resume">
            <h2 className="section__subheader">Resume</h2>
            <div className="testimonial__card1">
                <a href="https://www.boardinfinity.com/programs/college-courses"><h3>Summer Training Program</h3></a>
                <div><h3>Board Infinity</h3></div>
                <div><h5> Database Management Systems (DBMS)</h5></div>
                <ul style={{ lineHeight: 1.6, marginBottom: '20px', paddingLeft: '20px' }}>
                    <li>Strong grasp of DBMS evolution and core types.</li>
                    <li>Skilled in ER diagram creation and normalization (1NF–3NF).</li>
                    <li>Proficient in B/B+ Tree indexing for query optimization.</li>
                    <li>In-depth knowledge of transaction management: ACID, serializability, concurrency control.</li>
                </ul>
                <div><h5>SQL Proficiency</h5></div>
                <ul style={{ lineHeight: 1.6, marginBottom: '20px', paddingLeft: '20px' }}>
                    <li>Mastery of DDL, DML, DCL, TCL</li>
                    <li>Advanced querying: WHERE, ORDER BY, regex, string/boolean/grouping functions.</li>
                    <li>Expert in joins, subqueries, GROUP BY, HAVING, UNION, CASE, multi-table queries.</li>
                </ul>
                <div><h5>Relational & Non-Relational Databases</h5></div>
                <ul style={{ lineHeight: 1.6, marginBottom: '20px', paddingLeft: '20px' }}>
                    <li>Proficient in MySQL; clear distinction between SQL and NoSQL systems.</li>
                </ul>
                <h4>Learnt Tech <span>: MySQL, SQL</span></h4>
            </div>

            <h3 className="test">Education</h3>
            <div className="testimonial__grid">
                <div className="testimonial__card">
                    <h2>Btech</h2>
                    <p>2022 - present<br />Lovely Professional University</p>
                    <h4>8.06/10.00</h4>
                </div>
                <div className="testimonial__card">
                    <h2>Intermediate</h2>
                    <p>2020 - 2022<br />DKNP JR College</p>
                    <h4>957/1000</h4>
                </div>
                <div className="testimonial__card">
                    <h2>Secondary</h2>
                    <p>2019 - 2020<br />Sri Siddartha Educational Institutions</p>
                    <h4>10.00/10.00</h4>
                </div>
                <div className="about__btns">
                    <a href="/Resume.pdf" target="_blank" className="download__btn" rel="noopener noreferrer">
                        Download CV
                    </a>
                </div>
            </div>

            <h2 className="section__subheader" style={{ marginTop: '4rem' }}>Certifications / Courses</h2>
            <div className="testimonial__grid">
                <div className="testimonial__card">
                    <h2>NPTEL</h2>
                    <p>
                        <img src={cert1} alt="Certificate" />
                        Earned a prestigious cloud computing certificate from Swayam, an initiative by the Indian Government, unlocking deep expertise in cloud computing technologies and their transformative applications.
                    </p>
                    <a href="https://drive.google.com/file/d/1kXMl26U8M9dGRxv2W_9ZGZ5N3DfTL2JC/view?usp=sharing"><h4>click Here</h4></a>
                </div>
                <div className="testimonial__card">
                    <h2>Coursera - Supervised Learning</h2>
                    <p>
                        <img src={cert2} alt="Certificate" />
                        Earned a Supervised Learning certificate through Coursera, a globally recognized online learning platform offering courses from top universities and institutions.
                    </p>
                    <a href="https://drive.google.com/file/d/10To75UJpChRRsKQdrSanRagJ7EbPhhMp/view?usp=sharing"><h4>click Here</h4></a>
                </div>
                <div className="testimonial__card">
                    <h2>Hacker rank - Python</h2>
                    <p>
                        <img src={cert3} alt="Certificate" />
                        Achieved a Python certification from HackerRank, demonstrating proficiency in core programming concepts and problem-solving skills.
                    </p>
                    <a href="https://www.hackerrank.com/certificates/b18906a3a19c"><h4>click Here</h4></a>
                </div>
                <div className="testimonial__card">
                    <h2>Coursera - Tableau</h2>
                    <p>
                        <img src={cert4} alt="Certificate" />
                        Completed a Tableau course on Coursera, gaining hands-on experience in data visualization, dashboard creation, and interactive analytics.
                    </p>
                    <a href="https://drive.google.com/file/d/1wL3HxfTMfYB-OstuJikaRAdDZVYf3-s3/view?usp=sharing"><h4>click Here</h4></a>
                </div>
                <div className="testimonial__card">
                    <h2>Coursera - C++</h2>
                    <p>
                        <img src={cert5} alt="Certificate" />
                        Completed a C++ programming course on Coursera, covering object-oriented principles, data structures, and algorithmic problem solving.
                    </p>
                    <a href="https://drive.google.com/file/d/1jjIG6ASvM0bo2-P_SIURsjUvIwdd348o/view?usp=sharing"><h4>click Here</h4></a>
                </div>
            </div>
        </section>
    );
};

export default Resume;
